M48
; DRILL file {KiCad 7.0.8} date Thu Nov 16 13:07:04 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-16T13:07:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.8752Y-4.3098
X3.8752Y-5.1583
X6.0646Y-4.3098
X6.0646Y-5.1583
T0
M30
